name: Package & publish Helm chart

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily sync with upstream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Fetch upstream chart
        run: |
          git clone --depth 1 https://github.com/openreplay/openreplay.git
          # make sure the parent dir exists (Git ignores empty dirs)
          mkdir -p charts
          # copy the upstream chart in; trailing slash keeps only the contents
          rsync -a --delete \
            openreplay/scripts/helmcharts/openreplay/ charts/openreplay/

      - name: Copy upstream default values
        run: |
          cp openreplay/scripts/helmcharts/vars.yaml charts/openreplay/values.yaml

          # keep ingress-nginx on
          yq -i '.ingress-nginx.enabled = true' charts/openreplay/values.yaml

          # admission-webhook patch NetworkPolicy
          yq -i '.ingress-nginx.controller.admissionWebhooks.patch.networkPolicy.enabled = false' charts/openreplay/values.yaml

          # default-backend PSP and other bits
          yq -i '.ingress-nginx.podSecurityPolicy.enabled = false' charts/openreplay/values.yaml

          # ORSecureAccess boolean
          yq -i '.global.ORSecureAccess = false' charts/openreplay/values.yaml

          # migration Job wants an annotations map
          yq -i '.migrationJob.podAnnotations = {}' charts/openreplay/values.yaml

          # controller-level NetworkPolicy gate
          yq -i '.ingress-nginx.controller.networkPolicy.enabled = false' charts/openreplay/values.yaml

      - name: Patch alerts template (quote randAlphaNum)
        run: |
          # quote ANY '{{randAlphaNum 20}}' variant (spaces or not)
          sed -Ei \
            's/\{\{[[:space:]]*randAlphaNum[[:space:]]*20[[:space:]]*\}\}/{{ randAlphaNum 20 | quote }}/g' \
            charts/openreplay/charts/alerts/templates/deployment.yaml

      - name: Set chart version to 0.1.${{ github.run_number }}
        run: |
          yq -i '.version = "0.1.${{ github.run_number }}"' charts/openreplay/Chart.yaml

      - name: Build dependencies & package
        run: |
          helm dependency update charts/openreplay
          mkdir -p docs
          helm package charts/openreplay --destination docs

      - name: Re-generate repo index
        run: |
          helm repo index docs \
            --url https://floki-inu.github.io/openreplay-helm

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
