name: Package & publish Helm chart

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily sync with upstream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Fetch upstream chart
        run: |
          git clone --depth 1 https://github.com/openreplay/openreplay.git
          # make sure the parent dir exists (Git ignores empty dirs)
          mkdir -p charts
          # copy the upstream chart in; trailing slash keeps only the contents
          rsync -a --delete \
            openreplay/scripts/helmcharts/openreplay/ charts/openreplay/

      - name: Copy upstream default values
        run: |
          # put the upstream vars.yaml in place as this chart's values.yaml
          cp openreplay/scripts/helmcharts/vars.yaml \
             charts/openreplay/values.yaml
          # make sure ingress-nginx is ON by default
          yq -i '.ingress-nginx.enabled = true' charts/openreplay/values.yaml

      - name: Patch alerts template (quote randAlphaNum)
        run: |
          # quote ANY '{{randAlphaNum 20}}' variant (spaces or not)
          sed -Ei \
            's/\{\{[[:space:]]*randAlphaNum[[:space:]]*20[[:space:]]*\}\}/{{ randAlphaNum 20 | quote }}/g' \
            charts/openreplay/charts/alerts/templates/deployment.yaml

      - name: Bump chart version to force new .tgz
        run: |
          # read current semver (e.g. 0.1.0), bump the patch part
          ver=$(yq '.version' charts/openreplay/Chart.yaml)
          major=$(cut -d. -f1 <<<"$ver")
          minor=$(cut -d. -f2 <<<"$ver")
          patch=$(cut -d. -f3 <<<"$ver")
          new_patch=$((patch + 1))
          new_ver="${major}.${minor}.${new_patch}"
          yq -i ".version = \"${new_ver}\"" charts/openreplay/Chart.yaml
          echo "🔖 bumped chart version to ${new_ver}"

      - name: Build dependencies & package
        run: |
          helm dependency update charts/openreplay
          mkdir -p docs
          helm package charts/openreplay --destination docs

      - name: Re-generate repo index
        run: |
          helm repo index docs \
            --url https://floki-inu.github.io/openreplay-helm

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
