name: Package & publish Helm chart

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily sync with upstream

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4
      
      - name: Download templater
        run: |
          curl https://i.jpillora.com/rjshrjndrn/templater! | bash

      - name: Fetch upstream chart
        run: |
          git clone --depth 1 https://github.com/openreplay/openreplay.git
          # overwrite the randAlphaNum to a random string matching the criteria
          templater -i openreplay/scripts/helmcharts/vars.yaml -o openreplay/scripts/helmcharts/vars.yaml
          # make sure the parent dir exists (Git ignores empty dirs)
          mkdir -p charts
          # copy the upstream chart in; trailing slash keeps only the contents
          rsync -a --delete \
            --exclude 'charts/alerts' \
            openreplay/scripts/helmcharts/openreplay/ charts/openreplay/

      - name: Quote any randAlphaNum that appears in a YAML key
        run: |
          # Look through every YAML template that still contains 'randAlphaNum'
          # and quote the call so it becomes a *value*, not a map key.
          # We replace the whole {{ ... }} block with a quoted version.
          find charts/openreplay -name '*.yaml' -print0 \
          | xargs -0 perl -0777 -pe '
              s/\{\{[^\}]*?randAlphaNum[^\}]*?\}\}/"{{ randAlphaNum 20 | quote }}"/gs
          ' -i

      - name: Copy upstream default values
        run: |
          cp openreplay/scripts/helmcharts/vars.yaml charts/openreplay/values.yaml
          yq -i '.ingress-nginx.enabled = true' charts/openreplay/values.yaml
          yq -i '.ingress-nginx.controller.networkPolicy.enabled = false' charts/openreplay/values.yaml
          yq -i '.ingress-nginx.controller.admissionWebhooks.patch.networkPolicy.enabled = false' charts/openreplay/values.yaml
          yq -i '.ingress-nginx.podSecurityPolicy.enabled = false' charts/openreplay/values.yaml
          yq -i '.global.ORSecureAccess = false' charts/openreplay/values.yaml
          yq -i '.migrationJob.podAnnotations = {}' charts/openreplay/values.yaml
          yq -i '.migration.env = []' charts/openreplay/values.yaml

      - name: Set chart version to 0.1.${{ github.run_number }}
        run: |
          yq -i '.version = "0.1.${{ github.run_number }}"' charts/openreplay/Chart.yaml

      - name: Build dependencies & package
        run: |
          helm dependency update charts/openreplay
          mkdir -p docs
          helm package charts/openreplay --destination docs

      - name: Re-generate repo index
        run: |
          helm repo index docs \
            --url https://floki-inu.github.io/openreplay-helm

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
